### DISCUSSION TITLE
FODO Cell Example

### DISCUSSION THREAD

**Discussion by EZoni** [pals-project/pals#52] [General]
Based on discussions with @jlvay and @cemitch99, we would like to compare three different variations of a YAML file defining a FODO cell example and discuss with the community which one(s) may be preferred, as far as PALS is concerned. For the choice of parameters, we used the ImpactX example described [here](https://impactx.readthedocs.io/en/latest/usage/examples/fodo/README.html).

1. Option consistent with PALS, as is:
    ```yaml
    Lattice:
      - Branch: fodo
    BeamLine:
      name: fodo
      line:
        - item:
            Element:
              name: drift1
              kind: Drift
              length: 0.25
        - item:
            Element:
              name: quad1
              kind: Quadrupole  
              length: 1.0
              MagneticMultipoleP:
                Kn1: 1.0
        - item:
            Element:
              name: drift2
              kind: Drift  
              length: 0.5
        - item:
            Element:
              name: quad2 
              kind: Quadrupole
              length: 1.0
              MagneticMultipoleP:
                Kn1: -1.0
        - item:
            Element:
              name: drift3
              kind: Drift
              length: 0.5 
    ```

2. Option without `item` and `Element`, using element's name as identifier:
    ```yaml
    Lattice:
      - Branch: fodo
    BeamLine:
      name: fodo
      line:
        - Drift1:
            kind: Drift
            length: 0.25
        - Quad1:
            kind: Quadrupole  
            length: 1.0
            MagneticMultipoleP:
              Kn1: 1.0
        - Drift2:
            kind: Drift  
            length: 0.5
        - Quad2:
            kind: Quadrupole
            length: 1.0
            MagneticMultipoleP:
              Kn1: -1.0
        - Drift3:
            kind: Drift
            length: 0.5 
    ```

3. Option without `item` and `Element`, using element's kind as identifier:
    ```yaml
    Lattice:
      - Branch: fodo
    BeamLine:
      name: fodo
      line:
        - Drift:
            name: drift1
            length: 0.25
        - Quadrupole:
            name: quad1
            length: 1.0
            MagneticMultipoleP:
              Kn1: 1.0
        - Drift:
            name: drift2
            length: 0.5
        - Quadrupole:
            name: quad2
            length: 1.0
            MagneticMultipoleP:
              Kn1: -1.0
        - Drift:
            name: drift3
            length: 0.5 
    ```

**Comment by DavidSagan** [comment]
@EZoni The problem is what is displayed does not show how things will work with more complex constructions. Can you modify this to show how these options will work with elements defined outside the `BeamLine` as well as with element inheritance, repetition, and sublines? Thanks.

**Reply by jlvay** [reply]
@DavidSagan . Here is an attempt with inheritance and repetition using Option 2:

```yaml
Lattice:
  - Branch: fodo
BeamLine:
  name: fodo
  line:
    - Drift1:
        kind: Drift
        length: 0.25
    - ap1:
        kind: Aperture
        ApertureP:
           x_limit: [-0.03, 0.04]
    - Quad1:
        kind: Quadrupole  
        length: 1.0
        MagneticMultipoleP:
          Kn1: 1.0
    - Drift2:
        kind: Drift  
        length: 0.5
    - ap2:
        kind: Aperture
        inherit: ap1
        ApertureP:
           y_limit: [-0.02, 0.05]
    - Quad2:
        kind: Quadrupole
        length: 1.0
        MagneticMultipoleP:
          Kn1: -1.0
    - Drift3:
        kind: Drift
        length: 0.5 
Beamline:
  name: full_line
  line:
    - fodo:
        repetition: 3
```

**Comment by DavidSagan** [comment]
Another option would be to just get rid if `item`:
```yaml
Element:
   name: quad1
     kind: Quadrupole  
     length: 1.0
     MagneticMultipoleP:
       Kn1: 1.0

Lattice:
  - Branch: fodo

BeamLine:
  name: fodo
  line:
    - Element:
          name: drift1
          kind: Drift
          length: 0.25
    - Element:
         - Inherit: quad1
         - name: quad1_A
         - length: 2.0
    - Element:
          repetition: 2
          direction: -1
          name: drift2
          kind: Drift  
          length: 0.5
    - Element:
          name: quad2 
          kind: Quadrupole
          length: 1.0
          MagneticMultipoleP:
            Kn1: -1.0

Beamline:
  name: full_line
  line:
    - BeamLine:
        name: fodo
        repetition: 3
    - Element:
          name: drift3
          kind: Drift
          length: 0.5 
```

**Reply by jlvay** [reply]
Our proposal is to get rid of both `item` and `Element`, which seem redundant. Hence, for your example below, using either the name or the kind of the element in place of `Element` directly. I.e., replace
```yaml
    - Element:
          name: drift3
          kind: Drift
          length: 0.5 
 ```
 with either 
```yaml
    - drift3:
          kind: Drift
          length: 0.5 
 ```
or
```yaml
    - Drift:
          name: drift3
          length: 0.5 
 ```
 Just trying to have a compact notation. In part a matter of taste, of course.

**Reply by DavidSagan** [reply]
Yes but to decide on any changes we should consider all possibilities.

**Reply by jlvay** [reply]
Indeed. Hence the discussion here and on zoom tomorrow. :-)

**Reply by DavidSagan** [reply]
The of the syntax in the PR is that stuff like `reputation` would appear outside of the `Element` definition since this is not part of the element and this makes the syntax cleaner. EG:
```yaml
Element:
  name: Q1
  ...

BeamLine:
  line:
    - item:
         name: Q1
         repetition: 3
         direction: -1
         placement:
            offset: 37.5
            base_item: thingA
            from_point: EXIT_END
```
The syntax you are proposing is fine for uncomplicated things but I think a more segmented syntax is better otherwise.

**Reply by DavidSagan** [reply]
Also I suspect that lattices will generally use element definitions separate from the beam lines. So to rewrite your first example:
```yaml
Element:
   name: drift1
   kind: Drift
   length: 0.25

Element:
   name: quad1
   kind: Quadrupole  
   length: 1.0
   MagneticMultipoleP:
       Kn1: 1.0

Lattice:
  - Branch: fodo
  - 
BeamLine:
  name: fodo
  line:
    - item: drift1
    - item: quad1
    - item: drift2
    - item: quad2
```

**Reply by jlvay** [reply]
For your last two examples, I would propose:
```yaml
Element:
  name: Q1
  ...

BeamLine:
  line:
    - Q1:
         repetition: 3
         direction: -1
         placement:
            offset: 37.5
            base_item: thingA
            from_point: EXIT_END
```

and 

```yaml
Element:
   name: drift1
   kind: Drift
   length: 0.25

Element:
   name: quad1
   kind: Quadrupole  
   length: 1.0
   MagneticMultipoleP:
       Kn1: 1.0

Lattice:
  - Branch: fodo

BeamLine:
  name: fodo
  line:
    - drift1
    - quad1
    - drift2
    - quad2
```

**Reply by jlvay** [reply]
Option 4:
```yaml
Lattice:
  - Branch: branch_name
      beamline: fodo

BeamLine: fodo
  line:
    - Drift: drift1
        length: 0.25
    - Quadrupole: quad1
        length: 1.0
        MagneticMultipoleP:
          Kn1: 1.0
    - Drift: drift2
        length: 0.5
    - Quadrupole: quad2
        length: 1.0
        MagneticMultipoleP:
          Kn1: -1.0
    - Drift: drift3
        length: 0.5 
 ```

**Reply by jlvay** [reply]
```yaml

Drift: drift1
   length: 0.25

Quadrupole: quad1
   length: 1.0
   MagneticMultipoleP:
       Kn1: 1.0

Lattice:
  - Branch: branch_name
      beamline: fodo

BeamLine: fodo
  line:
    - drift1
    - quad1
    - drift2
    - quad2

```

**Reply by jlvay** [reply]
@campa-consortium/pals-contributors 

Here is a more complex example:

```yaml
Quadrupole: thingA
  length: 1.0
  MagneticMultipoleP:
    Kn1: -1.0

Quadrupole: thingB
  length: 1.0
  MagneticMultipoleP:
    Kn1: 1.0

Marker: thingC

BeamLine: subline1
  zero_point: thingC
  line:
    - thingA
    - thingB
    - thingC      

BeamLine: inj_line
  multipass: True
  length: 37.8
  line:
    - thingA
    - thingB  
        placement:
          offset: 0.1
          to_point: ENTRANCE_END
          base_item: thingA
          from_point: EXIT_END
    - Drift: drift1      # This item contains an is reversed.
        direction: -1
        length: 1.
        repetition: 3    # This iterated three times
    - subline1     
        placement:
          offset: 0.1
          to_point: ZERO_POINT
          base_item: drift1
          from_point: EXIT_END
```

This more complex example shows that the new syntax is viable (did not encounter any showstopper). Hence, the team will go forward and implement it unless there is any serious concern. Please let us know ASAP of any concern or objection.
