### DISCUSSION TITLE
Organizing parameters

### DISCUSSION THREAD

**Discussion by danielkallendorf** [pals-project/pals#57] [General]
Hey,
I was trying to implement a new parameter group for (non-blocking) matter, like a target, detector, wedge, ...
Below is my idea of the description of a rough, 1mm $\mathrm{C}_9\mathrm{H}_10$ scintillator plate.
```yaml
MatterP:
    thickness: 1E-3
    density: 1.09E3
    matter1:
        element: H
        mass: 1.08
        ratio: 10
    matter2:
        element: C
        mass: 12
        ratio: 9
    defect: 1E-2
```
And the description for a $7\deg=0.12\mathrm{rad}$ Cu wedge-degrader (an angled piece of copper):
```yaml
MatterP:
    thickness: 1.28E-2
    density: 8.92E3
    matter1:
        element: Cu
        mass: 63.5
        ratio: 1
    defect: 1E-3
    wedge:
        x-angle: 0.12
        y-angle: 0
```

 
Questions:
Do we support parameter sub-groups? If so: How do we describe a parameter of type parameter-group?
Do we have any notation for optional and default values? The parameters of `wedge` are usually 0 for most matter.
How can I describe an N-dim polynomial in the standard? The thickness might be described as a 2d polynomial coefficients.

Best,
Daniel
